// tenants.config.js
module.exports = {
  umpire: {
    name: "4dot6 Umpire Ball Counter",
    bundleId: "com.4dot6.cricketballandovercounter",
    package: "com.cricketovercounterapp",
    scheme: "com.4dot6.cricketballandovercounter",
    color: "#12c2e9",
    splashColor: "#12c2e9",
    icon: "./assets/images/splash-icon-4dot6.png",
    iosIcon: "./assets/ios-icon.png",
    splash: "./assets/images/splash-icon-4dot6.png",
    googleIos: "./config/umpire/GoogleService-Info.plist",
    googleAndroid: "./config/umpire/google-services.json",
    // --- UI & THEME STRATEGY ---
    modes: [
      {
        id: "ball",
        label: "Ball Counter",
        primary: true,
        logo: "logo_ballCounterCard_trans",
      },
      {
        id: "score",
        label: "Scorebook",
        primary: false,
        logo: "logo_ballCounterCard",
      },
      {
        id: "liveScores",
        label: "Live Scores",
        primary: false,
        logo: "logo_ballCounterCard_trans",
      },
    ],
    theme: {
      headerLogo: "logo_umpire",
      modeSelectionBg: "rgba(0,0,0,1)",
      modeHeaderBg: "rgba(0,0,0,1)",
      headerTextColor: "#ffffff",
      backgroundImage: null, // Umpire uses solid black
      logoAspectRatio: 1.8,
      cardBorderColor: "transparent",
      cardBorderWidth: 0,
      cardBg: "#12c2e9",
      cardTextColor: "#ffffff",
      ballBg: "#12c2e9",
      ballText: "#ffffff",
      scoreBg: "#ffffff",
      scoreText: "#12c2e9",
      // 👇 ADD THIS
      actionTabs: {
        undoColor: "#c471ed",
        dotColor: "#FFF8F0",
        dotIconColor: "#12c2e9",
        plusColor: "#77dd77",
        labelColor: "#fff",
        dotLabelColor: "#12c2e9",
      },
    },
    features: {
      liveStreaming: false,
      showJuniorPrompt: true, // 4dot6 asks if they should use LittleWicket
      primaryMode: "ball",
    },
  },
  littlewicket: {
    name: "LittleWicket Cricket Scorebook",
    bundleId: "com.fourdootsix.cricketscorebookbyc",
    package: "com.cricketscorebookbyc",
    scheme: "com.fourdootsix.cricketscorebookbyc",
    color: "#2E7D32",
    splashColor: "#ffffff",
    icon: "./assets/images/icon-littlewicket.png",
    iosIcon: "./assets/images/ios-icon-littlewicket.png",
    splash: "./assets/images/splash-littlewicket.png",
    googleIos: "./config/littlewicket/GoogleService-Info.plist",
    googleAndroid: "./config/littlewicket/google-services.json",
    // --- UI & THEME STRATEGY ---
    modes: [
      {
        id: "score",
        label: "Scorebook",
        primary: true,
        logo: "logo_littlewicketCardBall",
      },
      {
        id: "ball",
        label: "Ball Counter",
        primary: false,
        logo: "logo_littlewicketCardBall_trans",
      },
      {
        id: "liveScores",
        label: "Live Scores",
        primary: false,
        logo: "logo_littlewicketCardBall",
      },
    ],
    theme: {
      headerLogo: "logo_littlewicket",
      modeSelectionBg: "#ffffff",
      modeHeaderBg: "transparent",
      headerTextColor: "#000000",
      backgroundImage: "icon_littlewicket",
      logoAspectRatio: 4.1,
      cardBorderColor: "#e9df36",
      cardBorderWidth: 2,
      cardBg: "#ffffff",
      cardTextColor: "#e9df36",
      scoreText: "#12c2e9",
      scoreBg: "#ffffff",
      ballBg: "#ffffff",
      ballText: "#e9df36",
      scoreBorderColor: "#12c2e9",
      ballBorderColor: "#e9df36",
      actionTabs: {
        undoColor: "#e2339c",
        dotColor: "#e9df36",
        dotIconColor: "#666",
        plusColor: "#77dd77",
        labelColor: "#fff",
        dotLabelColor: "#666",
      },
    },
    features: {
      liveStreaming: true,
      showJuniorPrompt: false, // LittleWicket doesn't need to prompt
      primaryMode: "score",
    },
  },
};
